module.exports.getThoughts = require('./getThoughts')
module.exports.addThought = require('./addThought')
module.exports.deleteThought = require('./deleteThought')
module.exports.updateThought = require('./updateThought')
module.exports.likeThought = require('./likeThought')